### ISSUE TITLE
unclear Pod Microsegmentation chapter, step 1.a.

### ISSUE THREAD

**Issue by avoidik** [tigera-solutions/jessie-workshop-demo#2]
hello,

could you please clarify what kind of policy meant behind the "Create logging policy for storefront application in platform tier" step?

ref.
https://github.com/tigera-solutions/calicocloud-kaas-workshop-demo/blob/main/modules/pod-microsegmentation.md

**Comment by jessieziyuantang** [comment]
Thanks for noting that. I used to have a logging policy for my storefront in platform tier because it will write logs to another microservice in different namespace, but I took it out as people usually prefer to push log in ELK or in their existing SIEM not keep them in k8s cluster. I will remove this line.

**Comment by jessieziyuantang** [comment]
Remove the unclear text from module 'Pod Microsegmentation'
